/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fire_Guns_Dudung_Peaky_Blinder;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS TUF GAMING
 */
public class barang extends javax.swing.JFrame {

    /**
     * Creates new form kategori_v1
     */
    public barang() {
        initComponents();
        table_update();
        kategori_v1();
        merk();
    }
    
    Connection con7;
    PreparedStatement pst7;
    
    public class KATEGORIITEM
    {
        int KODE;
        String NAMA;
        
        public KATEGORIITEM(int KODE, String NAMA)
        {
            this.KODE = KODE;
            this.NAMA = NAMA;
        
        }
        
        public String toString()
        {
            return NAMA;
        }
        
    
    }
    
     public class MERKITEM
    {
        int KODE;
        String NAMA;
        
        public MERKITEM(int KODE, String NAMA)
        {
            this.KODE = KODE;
            this.NAMA = NAMA;
        
        }
        
        public String toString()
        {
            return NAMA;
        }
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void kategori_v1()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con7 = DriverManager.getConnection("jdbc:mysql://localhost/hp","root","");
             pst7 = con7.prepareStatement("select * from KATEGORI");
             ResultSet rs7 = pst7.executeQuery();
             tkat.removeAllItems();
             
             while(rs7.next())
             {
                 tkat.addItem(new KATEGORIITEM(rs7.getInt(1),rs7.getString(2)));
             
             }
             
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
     private void merk()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con7 = DriverManager.getConnection("jdbc:mysql://localhost/hp","root","");
             pst7 = con7.prepareStatement("select * from MERK");
             ResultSet rs7 = pst7.executeQuery();
             tmerk.removeAllItems();
             
             while(rs7.next())
             {
                 tmerk.addItem(new MERKITEM(rs7.getInt(1),rs7.getString(2)));
             
             }
             
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
    
    
    
    
    
    private void table_update()
    {
        try {
            int K;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                 con7 = DriverManager.getConnection("jdbc:mysql://localhost/hp","root","");
                 pst7 = con7.prepareStatement("select B.KODE,B.BARANG,B.DETAIL,K.KATEGORI,M.MERK,B.HARGA_BIAYA,B.HARGA_SATUAN,B.QUANTITY,B.BARCODE,B.STATUS from BARANG B,KATEGORI K, MERK M where B.KATEGORI_KODE = K.KODE and B.MERK_KODE = M.KODE");
                 ResultSet rs7 = pst7.executeQuery();
                 
                 ResultSetMetaData rsd7 = rs7.getMetaData();
                 K = rsd7.getColumnCount();
                 
                 DefaultTableModel d7 = (DefaultTableModel)jTable1.getModel();
                 d7.setRowCount(0);
                 
                 while(rs7.next())
                 {
                     Vector v7 = new Vector();
                     
                     for (int i=1; i<=K; i++)
                     {
                         v7.add(rs7.getString("KODE"));
                         v7.add(rs7.getString("BARANG"));
                         v7.add(rs7.getString("DETAIL"));
                         v7.add(rs7.getString("KATEGORI"));
                         v7.add(rs7.getString("MERK"));
                         v7.add(rs7.getString("HARGA_BIAYA"));
                         v7.add(rs7.getString("HARGA_SATUAN"));
                         v7.add(rs7.getString("QUANTITY"));
                         v7.add(rs7.getString("BARCODE"));
                         v7.add(rs7.getString("STATUS"));
                         
                     }
                     d7.addRow(v7);
                 
                 }
                 
                 
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tbarang = new javax.swing.JTextField();
        tstat = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tbiaya = new javax.swing.JTextField();
        tsatuan = new javax.swing.JTextField();
        tquan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tdetail = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        tkat = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        tmerk = new javax.swing.JComboBox();
        tbarcode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel1.setText("MERK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel2.setText("KATEGORI");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel3.setText("KALKULASI");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel4.setText("KELUAR");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel5.setText("BARANG");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel7.setText("PEAKY BLINDER");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel8.setText("BARANG");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("FIRE GUNS");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BARANG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel10.setText("BARANG");

        jLabel11.setText("STATUS");

        tstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT_GOOD", "HALF_GOOD", "GOOD" }));
        tstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstatActionPerformed(evt);
            }
        });

        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("DETAIL");

        jLabel15.setText("HARGA_BIAYA");
        jLabel15.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jLabel15ComponentRemoved(evt);
            }
        });

        jLabel16.setText("HARGA_SATUAN");

        jLabel17.setText("QUANTITY");

        jLabel18.setText("BARCODE");

        tquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tquanActionPerformed(evt);
            }
        });

        tdetail.setColumns(20);
        tdetail.setRows(5);
        jScrollPane2.setViewportView(tdetail);

        jLabel19.setText("KATEGORI");

        jLabel20.setText("MERK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel15))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbiaya)
                    .addComponent(tmerk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbarang)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(tkat, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tquan)
                        .addComponent(tsatuan)
                        .addComponent(tstat, 0, 191, Short.MAX_VALUE)
                        .addComponent(tbarcode))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(tsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(tbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(tkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(tstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tmerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(tbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE", "BARANG", "DETAIL", "KATEGORI", "MERK", "HARGA_BIAYA", "HARGA_SATUAN", "QUANTITY", "BARCODE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(257, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(378, 378, 378)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(418, 418, 418)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(104, 104, 104)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d7 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        tbarang.setText(d7.getValueAt(selectIndex, 1).toString());
        tdetail.setText(d7.getValueAt(selectIndex, 2).toString());
        
        tkat.setSelectedItem(d7.getValueAt(selectIndex, 3).toString());
        tmerk.setSelectedItem(d7.getValueAt(selectIndex, 4).toString());
        
        tbiaya.setText(d7.getValueAt(selectIndex, 5).toString());
        tsatuan.setText(d7.getValueAt(selectIndex, 6).toString());
        tquan.setText(d7.getValueAt(selectIndex, 7).toString());
        tbarcode.setText(d7.getValueAt(selectIndex, 8).toString());
        
        tstat.setSelectedItem(d7.getValueAt(selectIndex, 9).toString());
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel15ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel15ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15ComponentRemoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d7 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();

        int KODE = Integer.parseInt(d7.getValueAt(selectIndex, 0).toString());

        int dialogResult = JOptionPane.showConfirmDialog(null, "ANDA YAKIN? 0_0??","YAKIN KAH ANDA? ^_0?",JOptionPane.YES_NO_OPTION);

        if(dialogResult == JOptionPane.YES_OPTION)
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con7 = DriverManager.getConnection("jdbc:mysql://localhost/hp","root","");
                pst7 = con7.prepareStatement("delete from BARANG where KODE=?");
                pst7.setInt(1, KODE);
                pst7.executeUpdate();

                JOptionPane.showMessageDialog(null, "TELAH DI HAPUS  x_x ");

                table_update();

                tbarang.setText("");
                tdetail.setText("");
                
                tkat.setSelectedIndex(-1);
                tmerk.setSelectedIndex(-1);
                
                tbiaya.setText("");
                tsatuan.setText("");
                tquan.setText("");
                tbarcode.setText("");
                
                tstat.setSelectedIndex(-1);
                tbarang.requestFocus();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d7 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();

        int KODE = Integer.parseInt(d7.getValueAt(selectIndex, 0).toString());
        String BARANG = tbarang.getText();
        String DETAIL = tdetail.getText();
        
        KATEGORIITEM ITEM = (KATEGORIITEM)tkat.getSelectedItem();
        MERKITEM ITEM2 = (MERKITEM)tmerk.getSelectedItem();
        
        String HARGA_BIAYA = tbiaya.getText();
        String HARGA_SATUAN = tsatuan.getText();
        String QUANTITY = tquan.getText();
        String BARCODE = tbarcode.getText();
        
        String STATUS = tstat.getSelectedItem().toString();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con7 = DriverManager.getConnection("jdbc:mysql://localhost/hp","root","");
            pst7 = con7.prepareStatement("update BARANG set BARANG=?,DETAIL=?,KATEGORI_KODE=?,MERK_KODE=?,HARGA_BIAYA=?,HARGA_SATUAN=?,QUANTITY=?,BARCODE=?,STATUS=? where KODE=?");
            pst7.setString(1, BARANG);
            pst7.setString(2, DETAIL);
            pst7.setInt(3, ITEM.KODE);
            pst7.setInt(4, ITEM2.KODE);
            pst7.setString(5, HARGA_BIAYA);
            pst7.setString(6, HARGA_SATUAN);
            pst7.setString(7, QUANTITY);
            pst7.setString(8, BARCODE);
            pst7.setString(9, STATUS);
            
            pst7.setInt(10, KODE);
            pst7.executeUpdate();
            JOptionPane.showMessageDialog(null, "TELAH DI UPDATE ^_^ ");

            table_update();

            tbarang.setText("");
            tdetail.setText("");
            tkat.setSelectedIndex(-1);
            tmerk.setSelectedIndex(-1);
            tbiaya.setText("");
            tsatuan.setText("");
            tquan.setText("");
            tbarcode.setText("");
            tstat.setSelectedIndex(-1);
            tbarang.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String BARANG = tbarang.getText();
        String DETAIL = tdetail.getText();
        
        KATEGORIITEM ITEM = (KATEGORIITEM)tkat.getSelectedItem();
        MERKITEM ITEM2 = (MERKITEM)tmerk.getSelectedItem();
        
        String HARGA_BIAYA = tbiaya.getText();
        String HARGA_SATUAN = tsatuan.getText();
        String QUANTITY = tquan.getText();
        String BARCODE = tbarcode.getText();
        
        String STATUS = tstat.getSelectedItem().toString();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con7 = DriverManager.getConnection("jdbc:mysql://localhost/hp","root","");
            pst7 = con7.prepareStatement("insert into BARANG (BARANG,DETAIL,KATEGORI_KODE,MERK_KODE,HARGA_BIAYA,HARGA_SATUAN,QUANTITY,BARCODE,STATUS)values(?,?,?,?,?,?,?,?,?)");
            pst7.setString(1, BARANG);
            pst7.setString(2, DETAIL);
            pst7.setInt(3, ITEM.KODE);
            pst7.setInt(4, ITEM2.KODE);
            pst7.setString(5, HARGA_BIAYA);
            pst7.setString(6, HARGA_SATUAN);
            pst7.setString(7, QUANTITY);
            pst7.setString(8, BARCODE);
            pst7.setString(9, STATUS);
            pst7.executeUpdate();
            JOptionPane.showMessageDialog(null, "TELAH DITAMBAHKAN -_- ^_^");

            table_update();

            tbarang.setText("");
            tdetail.setText("");
            tkat.setSelectedIndex(-1);
            tmerk.setSelectedIndex(-1);
            tbiaya.setText("");
            tsatuan.setText("");
            tquan.setText("");
            tbarcode.setText("");
            tstat.setSelectedIndex(-1);
            
            tbarang.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tstatActionPerformed

    private void tquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tquanActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        kalkulasi_v1 W = new kalkulasi_v1();
        this.hide();
        W.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         barang X = new barang();
        this.hide();
        X.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         merk Y = new merk();
        this.hide();
        Y.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        kategori_v1 Z = new kategori_v1();
        this.hide();
        Z.setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tbarang;
    private javax.swing.JTextField tbarcode;
    private javax.swing.JTextField tbiaya;
    private javax.swing.JTextArea tdetail;
    private javax.swing.JComboBox tkat;
    private javax.swing.JComboBox tmerk;
    private javax.swing.JTextField tquan;
    private javax.swing.JTextField tsatuan;
    private javax.swing.JComboBox<String> tstat;
    // End of variables declaration//GEN-END:variables
}
