/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fire_Guns_Dudung_Peaky_Blinder;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;
/**
 *
 * @author ASUS TUF GAMING
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public print() {
        initComponents();
    }
    
    String ZSUBTOTAL;
    String ZBAYAR;
    String ZBALANCE;
    
    public print(String SUBTOTAL, String BAYAR, String BALANCE,TableModel tableModel) throws PrinterException {
        initComponents();
        
        this.ZSUBTOTAL = SUBTOTAL;
        this.ZBAYAR = BAYAR;
        this.ZBALANCE = BALANCE;
        
        
        tprint.setText(tprint.getText()+"=============================================\n");
        tprint.setText(tprint.getText()+"=============PEAKY BLINDERS==========\n");
        tprint.setText(tprint.getText()+"===============FIRE GUNS===============\n");
        tprint.setText(tprint.getText()+"=============================================\n");
        tprint.setText(tprint.getText()+"\n");
        tprint.setText(tprint.getText()+"BARANG"+"\t"+"HARGA"+"\t"+"TOTAL");
        
        for(int i=0; i<tableModel.getRowCount(); i++)
        {
            String BARANG = (String) tableModel.getValueAt(i, 1);
            String HARGA = (String) tableModel.getValueAt(i, 2);
            int TOTAL = (int) tableModel.getValueAt(i, 4);
            tprint.setText(tprint.getText()+"                                           \n");
            tprint.setText(tprint.getText()+BARANG+"\t");
            tprint.setText(tprint.getText()+HARGA+"\t");
            tprint.setText(tprint.getText()+TOTAL+"\t");
            tprint.setText(tprint.getText()+"                                           \n");
        
        }
        tprint.setText(tprint.getText()+"\n");
        tprint.setText(tprint.getText()+ "          "+"SUBTOTAL.= "+SUBTOTAL+"\n");
        tprint.setText(tprint.getText()+ "          "+"BAYAR....= "+BAYAR+"\n");
        tprint.setText(tprint.getText()+ "          "+"BALANCE..= "+BALANCE+"\n");
        
        tprint.setText(tprint.getText()+"===============TERIMA KASIH===================\n");
        tprint.setText(tprint.getText()+"==============================================\n");
        
       tprint.print();
        
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tprint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tprint.setColumns(20);
        tprint.setRows(5);
        jScrollPane2.setViewportView(tprint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tprint;
    // End of variables declaration//GEN-END:variables
}
